// This file is auto-generated by @hey-api/openapi-ts

import { type Options as ClientOptions, type TDataShape, type Client, formDataBodySerializer } from '@hey-api/client-fetch';
import type { FileListenerUploadFileUploadPostData, FileListenerUploadFileUploadPostError, FileListenerDownloadFileDownloadGetData, FileListenerDownloadFileDownloadGetError, FileListenerListFilesListGetData, FileListenerListFilesListGetResponse, FileListenerListFilesListGetError } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Filelistener.Upload File
 */
export const fileListenerUploadFileUploadPost = <ThrowOnError extends boolean = false>(options: Options<FileListenerUploadFileUploadPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<unknown, FileListenerUploadFileUploadPostError, ThrowOnError>({
        ...formDataBodySerializer,
        url: '/upload',
        ...options,
        headers: {
            'Content-Type': null,
            ...options?.headers
        }
    });
};

/**
 * Filelistener.Download File
 */
export const fileListenerDownloadFileDownloadGet = <ThrowOnError extends boolean = false>(options: Options<FileListenerDownloadFileDownloadGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<unknown, FileListenerDownloadFileDownloadGetError, ThrowOnError>({
        url: '/download',
        ...options
    });
};

/**
 * Filelistener.List Files
 */
export const fileListenerListFilesListGet = <ThrowOnError extends boolean = false>(options: Options<FileListenerListFilesListGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<FileListenerListFilesListGetResponse, FileListenerListFilesListGetError, ThrowOnError>({
        url: '/list',
        ...options
    });
};