// This file is auto-generated by @hey-api/openapi-ts

export type BodyFileListenerUploadFileUploadPost = {
    file: Blob | File;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type ListFilesResponse = {
    files: Array<string>;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type FileListenerUploadFileUploadPostData = {
    body: BodyFileListenerUploadFileUploadPost;
    headers?: {
        'x-request-id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/upload';
};

export type FileListenerUploadFileUploadPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FileListenerUploadFileUploadPostError = FileListenerUploadFileUploadPostErrors[keyof FileListenerUploadFileUploadPostErrors];

export type FileListenerUploadFileUploadPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type FileListenerDownloadFileDownloadGetData = {
    body?: never;
    path?: never;
    query: {
        request_id: unknown;
    };
    url: '/download';
};

export type FileListenerDownloadFileDownloadGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FileListenerDownloadFileDownloadGetError = FileListenerDownloadFileDownloadGetErrors[keyof FileListenerDownloadFileDownloadGetErrors];

export type FileListenerDownloadFileDownloadGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type FileListenerListFilesListGetData = {
    body?: never;
    path?: never;
    query: {
        request_id: unknown;
    };
    url: '/list';
};

export type FileListenerListFilesListGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FileListenerListFilesListGetError = FileListenerListFilesListGetErrors[keyof FileListenerListFilesListGetErrors];

export type FileListenerListFilesListGetResponses = {
    /**
     * Successful Response
     */
    200: ListFilesResponse;
};

export type FileListenerListFilesListGetResponse = FileListenerListFilesListGetResponses[keyof FileListenerListFilesListGetResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};